Backend bad solution
artem-berlin/nf-project pull request #1
Opened 2022-03-31 11:26 UTC by artem-berlin

after first review!

2022-03-31 12:03 UTC, gossie requested changes

2022-03-31 12:03 UTC, gossie commented on backend/pom.xml
> +        <dependency>
Die drei folgenden dependencies brauchst du nicht. Stattdessen:
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>
```

2022-03-31 12:03 UTC, gossie commented on backend/pom.xml
> +            <version>1.18.22</version>
Die Version kannst du löschen. Stattdessen `<optional>true</optional>`

2022-04-04 04:50 UTC, artem-berlin commented on backend/pom.xml
> +        <dependency>
Done.

2022-04-04 04:50 UTC, artem-berlin commented on backend/pom.xml
> +            <version>1.18.22</version>
Done.

2022-04-04 05:56 UTC, gossie approved these changes

2022-04-07 11:38 UTC, artem-berlin commented
merge1

2022-04-07 11:38 UTC, artem-berlin commented
merge2

2022-04-07 11:38 UTC, closed without merging